image:
  repository: shirleycutie/complete-devops-project
  tag: e205535
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enable: false

serviceAccount:
  enable: false

autoscaling:
  enable: false